# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u540d\u79f0')),
                ('saperateNumber', models.IntegerField(verbose_name='\u5206\u5c4f\u6570')),
                ('content', models.CharField(max_length=200, verbose_name='\u5185\u5bb9')),
                ('pos', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4d\u7f6e')),
                ('polling', models.BooleanField(default=False, verbose_name='\u8f6e\u5de1\u72b6\u6001')),
                ('pollingPos', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u8f6e\u5de1\u4f4d\u7f6e')),
                ('pollingTime', models.IntegerField(default=15, verbose_name='\u8f6e\u5de1\u95f4\u9694\u65f6\u95f4(\u79d2)')),
                ('active', models.BooleanField(default=False, verbose_name='\u663e\u793a\u5668\u662f\u5426\u6fc0\u6d3b')),
                ('monitorName', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u663e\u793a\u5668\u540d\u79f0')),
                ('resolution', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u663e\u793a\u5668\u5206\u8fa8\u7387')),
                ('productID', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u663e\u793a\u5668\u4ea7\u54c1ID')),
            ],
        ),
        migrations.CreateModel(
            name='terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalIP', models.GenericIPAddressField(error_messages={'unique': '\u91cd\u590dIP,\u8bf7\u91cd\u65b0\u8f93\u5165!'}, unique=True, verbose_name='IP')),
                ('name', models.CharField(max_length=200, verbose_name='\u7ec8\u7aef\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='terminalArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP')),
                ('name', models.CharField(blank=True, max_length=190, null=True, verbose_name='\u540d\u79f0')),
                ('status', models.BooleanField(default=False, verbose_name='\u5f53\u524d\u72b6\u6001')),
            ],
        ),
    ]
