# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171108_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='inUse',
            field=models.BooleanField(default=False, verbose_name='window\u662f\u5426used'),
        ),
    ]
