# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_channel_inuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='inUse',
            field=models.BooleanField(default=True, verbose_name='window\u662f\u5426used'),
        ),
    ]
