# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hvs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hvs.proto',
  package='hvs',
  syntax='proto3',
  serialized_pb=_b('\n\thvs.proto\x12\x03hvs\"A\n\x08Terminal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07tstatus\x18\x04 \x01(\x08\"0\n\rTerminalArray\x12\x1f\n\x08terminal\x18\x01 \x03(\x0b\x32\r.hvs.Terminal\"\x9e\x01\n\x0e\x43hannelPolling\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0esaperateNumber\x18\x02 \x01(\x05\x12\r\n\x05style\x18\x03 \x01(\x05\x12\x13\n\x0bpollingTime\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x05 \x01(\x08\x12\r\n\x05inuse\x18\x06 \x01(\x08\x12\x11\n\tisPolling\x18\x07 \x01(\x08\x12\x12\n\nterminalID\x18\x08 \x03(\t\"K\n\tTextStyle\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x10\n\x08location\x18\x02 \x01(\x05\x12\r\n\x05\x63olor\x18\x03 \x01(\x05\x12\x0f\n\x07showfps\x18\x04 \x01(\x08\"\xd6\x01\n\x0eWrapperMessage\x12\"\n\x03\x63pl\x18\x03 \x01(\x0b\x32\x13.hvs.ChannelPollingH\x00\x12 \n\x02ta\x18\x04 \x01(\x0b\x32\x12.hvs.TerminalArrayH\x00\x12\x1c\n\x03tml\x18\x05 \x01(\x0b\x32\r.hvs.TerminalH\x00\x12\x15\n\x0b\x64\x65\x62ugStatus\x18\x06 \x01(\x03H\x00\x12\x1d\n\x13packetGrepperStatus\x18\x07 \x01(\x03H\x00\x12#\n\ttextstyle\x18\x08 \x01(\x0b\x32\x0e.hvs.TextStyleH\x00\x42\x05\n\x03msgb\x06proto3')
)




_TERMINAL = _descriptor.Descriptor(
  name='Terminal',
  full_name='hvs.Terminal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hvs.Terminal.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='hvs.Terminal.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='hvs.Terminal.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tstatus', full_name='hvs.Terminal.tstatus', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=83,
)


_TERMINALARRAY = _descriptor.Descriptor(
  name='TerminalArray',
  full_name='hvs.TerminalArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='terminal', full_name='hvs.TerminalArray.terminal', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=133,
)


_CHANNELPOLLING = _descriptor.Descriptor(
  name='ChannelPolling',
  full_name='hvs.ChannelPolling',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hvs.ChannelPolling.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='saperateNumber', full_name='hvs.ChannelPolling.saperateNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='style', full_name='hvs.ChannelPolling.style', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pollingTime', full_name='hvs.ChannelPolling.pollingTime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active', full_name='hvs.ChannelPolling.active', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inuse', full_name='hvs.ChannelPolling.inuse', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isPolling', full_name='hvs.ChannelPolling.isPolling', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='terminalID', full_name='hvs.ChannelPolling.terminalID', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=294,
)


_TEXTSTYLE = _descriptor.Descriptor(
  name='TextStyle',
  full_name='hvs.TextStyle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='hvs.TextStyle.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='hvs.TextStyle.location', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='hvs.TextStyle.color', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='showfps', full_name='hvs.TextStyle.showfps', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=371,
)


_WRAPPERMESSAGE = _descriptor.Descriptor(
  name='WrapperMessage',
  full_name='hvs.WrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpl', full_name='hvs.WrapperMessage.cpl', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ta', full_name='hvs.WrapperMessage.ta', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tml', full_name='hvs.WrapperMessage.tml', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debugStatus', full_name='hvs.WrapperMessage.debugStatus', index=3,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packetGrepperStatus', full_name='hvs.WrapperMessage.packetGrepperStatus', index=4,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='textstyle', full_name='hvs.WrapperMessage.textstyle', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='hvs.WrapperMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=374,
  serialized_end=588,
)

_TERMINALARRAY.fields_by_name['terminal'].message_type = _TERMINAL
_WRAPPERMESSAGE.fields_by_name['cpl'].message_type = _CHANNELPOLLING
_WRAPPERMESSAGE.fields_by_name['ta'].message_type = _TERMINALARRAY
_WRAPPERMESSAGE.fields_by_name['tml'].message_type = _TERMINAL
_WRAPPERMESSAGE.fields_by_name['textstyle'].message_type = _TEXTSTYLE
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['cpl'])
_WRAPPERMESSAGE.fields_by_name['cpl'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['ta'])
_WRAPPERMESSAGE.fields_by_name['ta'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['tml'])
_WRAPPERMESSAGE.fields_by_name['tml'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['debugStatus'])
_WRAPPERMESSAGE.fields_by_name['debugStatus'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['packetGrepperStatus'])
_WRAPPERMESSAGE.fields_by_name['packetGrepperStatus'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['textstyle'])
_WRAPPERMESSAGE.fields_by_name['textstyle'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['Terminal'] = _TERMINAL
DESCRIPTOR.message_types_by_name['TerminalArray'] = _TERMINALARRAY
DESCRIPTOR.message_types_by_name['ChannelPolling'] = _CHANNELPOLLING
DESCRIPTOR.message_types_by_name['TextStyle'] = _TEXTSTYLE
DESCRIPTOR.message_types_by_name['WrapperMessage'] = _WRAPPERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Terminal = _reflection.GeneratedProtocolMessageType('Terminal', (_message.Message,), dict(
  DESCRIPTOR = _TERMINAL,
  __module__ = 'hvs_pb2'
  # @@protoc_insertion_point(class_scope:hvs.Terminal)
  ))
_sym_db.RegisterMessage(Terminal)

TerminalArray = _reflection.GeneratedProtocolMessageType('TerminalArray', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALARRAY,
  __module__ = 'hvs_pb2'
  # @@protoc_insertion_point(class_scope:hvs.TerminalArray)
  ))
_sym_db.RegisterMessage(TerminalArray)

ChannelPolling = _reflection.GeneratedProtocolMessageType('ChannelPolling', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELPOLLING,
  __module__ = 'hvs_pb2'
  # @@protoc_insertion_point(class_scope:hvs.ChannelPolling)
  ))
_sym_db.RegisterMessage(ChannelPolling)

TextStyle = _reflection.GeneratedProtocolMessageType('TextStyle', (_message.Message,), dict(
  DESCRIPTOR = _TEXTSTYLE,
  __module__ = 'hvs_pb2'
  # @@protoc_insertion_point(class_scope:hvs.TextStyle)
  ))
_sym_db.RegisterMessage(TextStyle)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPERMESSAGE,
  __module__ = 'hvs_pb2'
  # @@protoc_insertion_point(class_scope:hvs.WrapperMessage)
  ))
_sym_db.RegisterMessage(WrapperMessage)


# @@protoc_insertion_point(module_scope)
